name: CD Workflow

on:
  push:
    branches:
      - main

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  IMAGE_NAME: registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Heroku login
        run: heroku container:login

      - name: Build and push docker image
        run: |
          docker build -t ${{env.IMAGE_NAME}} --build-arg BASE_API_URL=${{secrets.BASE_API_URL}} .
          docker push ${{env.IMAGE_NAME}}

      - name: Deploy to Heroku
        run: heroku container:release web -a ${{ secrets.HEROKU_APP_NAME }}
